name: build and push docker images

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/Checkout@v3
      
      - name: Setup docker build
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/Login-action@v2 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push java backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: techietech/java-backend:latest

      - name: Build and push node frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: techietech/node-frontend:latest

        
